#!/usr/bin/env python

import psycopg2
import os
import os.path
import sys

user     = 'odoo'
password = 'odoo'
host     = '172.19.0.3'
dbname   = 'odoo-db'
conn = psycopg2.connect(dbname = dbname, user = user, password = password, host = host)
cur = conn.cursor()

tdir = sys.argv[1]
if not os.path.exists(tdir):
    os.mkdir(tdir)

# 1. discover the tables
cur.execute("select tablename from pg_catalog.pg_tables where schemaname = 'public'")
r = cur.fetchone()
tables = []
while r:
    #print r[0]
    tables.append([r[0], None])
    r = cur.fetchone()

# 2. discover the primary keys
for t in tables:
    #print 'for %s' % t
    cur.execute("""select a.attname
        from pg_index i
        join pg_attribute a
        on a.attrelid = i.indrelid and a.attnum = ANY(i.indkey)
        where i.indrelid = '\"%s\"'::regclass and i.indisprimary;""" % t[0])
    r = cur.fetchone()
    ids = []
    while r:
        ids.append(r[0])
        r = cur.fetchone()
    if len(ids):
        t[1] = ids

# 3. get table contents
for t in tables:
    f = open('%s/%s' % (tdir, t[0]), 'w')
    sql = 'select * from %s' % t[0]
    if t[1]:
        sql = sql + ' order by %s' % ','.join(t[1])
    cur.execute(sql)
    r = cur.fetchone()
    while r:
        f.write(','.join([str(er) for er in r]) + '\n')
        r = cur.fetchone()
    f.close()
